/********************************************************/
/*  Class: Category.java                                */
/*  Generated by UML2Android                            */
/*  Author: Francisco Martinez Esteso                   */
/********************************************************/

package es.uclm.daui.datarunning;


import java.util.ArrayList;

public class Category implements PersistentDomainClass {

	public long _id = -1;
	public String name;

	@Override
	public long getId(DbHelper db) {
		if (_id==-1) { // _id not set yet.
			_id = db.createCategory(this);
		}
		return _id;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long __id) {
		_id = __id;
	}

	public String getName() {
		return name;
	}

	public void setName(String _name) {
		name =_name;
	}

}

