/********************************************************/
/*  Class: Club.java                                    */
/*  Generated by UML2Android                            */
/*  Author: Francisco Martinez Esteso                   */
/********************************************************/

package es.uclm.daui.datarunning;


import java.util.ArrayList;

public class Club implements PersistentDomainClass {

	public long _id = -1;

	public String Name;
	public String Locality;

	@Override
	public long getId(DbHelper db) {
		if (_id==-1) { // _id not set yet.
			_id = db.createClub(this);
		}
		return _id;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long __id) {
		_id = __id;
	}

	public String getName() {
		return Name;
	}

	public void setName(String _Name) {
		Name =_Name;
	}

	public String getLocality() {
		return Locality;
	}

	public void setLocality(String _Locality) {
		Locality =_Locality;
	}

}

