/********************************************************/
/*  Interface: PersistentDomainClass.java               */
/*  Generated by UML2Android                            */
/*  Author: Francisco Martinez Esteso                   */
/********************************************************/

package es.uclm.daui.datarunning;

public interface PersistentDomainClass {
    public long getId();
    public long getId(DbHelper db);
    public void setId(long __id);
}
