/********************************************************/
/*  Class: Position.java                                */
/*  Generated by UML2Android                            */
/*  Author: Francisco Martinez Esteso                   */
/********************************************************/

package es.uclm.daui.datarunning;


import java.util.ArrayList;

public class Position implements PersistentDomainClass {

	public long _id = -1;

	public User user;
	public Integer CategoryPosition;
	public Integer GeneralPosition;
 
	@Override
	public long getId(DbHelper db) {
		if (_id==-1) { // _id not set yet.
			_id = db.createPosition(this);
		}
		return _id;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long __id) {
		_id = __id;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User _user) {
		user =_user;
	}

	public Integer getCategoryPosition() {
		return CategoryPosition;
	}

	public void setCategoryPosition(Integer _CategoryPosition) {
		CategoryPosition =_CategoryPosition;
	}

	public Integer getGeneralPosition() {
		return GeneralPosition;
	}

	public void setGeneralPosition(Integer _GeneralPosition) {
		GeneralPosition =_GeneralPosition;
	}
}

