/********************************************************/
/*  Class: User.java                                    */
/*  Generated by UML2Android                            */
/*  Author: Francisco Martinez Esteso                   */
/********************************************************/

package es.uclm.daui.datarunning;


import java.util.ArrayList;

public class User implements PersistentDomainClass {

	public long _id = -1;

	public String name;
	public Integer age;
	public ArrayList<Classification> classifications = new ArrayList<Classification>();
	public ArrayList<Survey> surveys = new ArrayList<Survey>();
	public Category category;
	public Club club;

	@Override
	public long getId(DbHelper db) {
		if (_id==-1) { // _id not set yet.
			_id = db.createUser(this);
		}
		return _id;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long __id) {
		_id = __id;
	}

	public String getName() {
		return name;
	}

	public void setName(String _name) {
		name =_name;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer _age) {
		age =_age;
	}

	public ArrayList<Classification> getClassifications() {
		return classifications;
	}

	public void setClassifications(ArrayList<Classification> _classifications) {
		classifications =_classifications;
	}

	public void addClassification(Classification _classification) {
		classifications.add(_classification);
	}

	public void removeClassification(Classification _classification) {
		classifications.remove(_classification);
	}

	public ArrayList<Survey> getSurveys() {
		return surveys;
	}

	public void setSurveys(ArrayList<Survey> _surveys) {
		surveys =_surveys;
	}

	public void addSurvey(Survey _survey) {
		surveys.add(_survey);
		// _survey.setUser(getId()); /* Asign FK id. */
	}

	public void removeSurvey(Survey _survey) {
		surveys.remove(_survey);
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category _category) {
		category =_category;
	}

	public Club getClub() {
		return club;
	}

	public void setClub(Club _club) {
		club =_club;
	}

}

